name: CI - Frontend (Angular 16)

on:
    push:
        branches: ["main", "dev"]
        paths:
            - "front/**"
    pull_request:
        branches: ["main", "dev"]
        paths:
            - "front/**"
env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
    build-and-test:
        name: Build & Test Angular
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do código
              uses: actions/checkout@v4

            - name: Configurar Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18.x"
                  cache: "npm"
                  cache-dependency-path: front/package-lock.json

            - name: Instalar dependências
              run: npm ci
              working-directory: ./front

            # - name: Lint
            #   run: npm run lint
            #   working-directory: ./front

            # Deixei comentado por que não temos testes implementados ainda
            #   - name: Testes unitários
            #     run: npm run test -- --watch=false --browsers=ChromeHeadlessCI
            #     working-directory: ./front

            - name: Build de produção
              run: npm run build -- --configuration production
              working-directory: ./front

            - name: Publicar artefatos
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-build
                  path: ./front/dist/
                  retention-days: 7
